### ISSUE TITLE
Allow reactive calls to be cached

### ISSUE THREAD

**Issue by iagocanalejas** [iagocanalejas/retrocache#11]
Extend adapter-rxjava and adapter-rxjava2

**Comment by iagocanalejas** [comment]
Waiting until retrofit 2.2.0 official release

**Comment by adek** [comment]
It's a great library. Also waiting to be compatible with RxJavva2 and RxJava2CallAdapterFactory (https://github.com/square/retrofit/tree/master/retrofit-adapters/rxjava2)

**Comment by iagocanalejas** [comment]
Working on it, i am a bit out of time right now but hope it will be done soon. Ty
